name: Build & publish yaxp-common to crates.io

on:
  push:
    branches:
      - main
    paths:
      - 'crates/yaxp-common/src/**'
  pull_request:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Publish crate
        working-directory: crates/yaxp-common
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: cargo publish
